name: furniture_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/nav/

  fonts:
    - family: Hauora
      fonts:
        - asset: assets/fonts/Hauora-Bold.ttf
          weight: 700
        - asset: assets/fonts/Hauora-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Hauora-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Hauora-Light.ttf
          weight: 300
        - asset: assets/fonts/Hauora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Hauora-Regular.ttf
          weight: 400
        - asset: assets/fonts/Hauora-SemiBold.ttf
          weight: 600

  